### ISSUE TITLE
Configure Error

### ISSUE THREAD

**Issue by abiliocoelho** [mezielabs/adonis-stripe#12]
## Description

Showing error at configuration time

## Package version
adonis-stripe@1.0.4

## Error Message & Stack Trace
/Users/abiliocoelho/www/dev/stripe/node_modules/@adonisjs/core/build/src/Ignitor/SignalsListener/index.js:50
            this.application.logger.fatal(error, '"uncaughtException" detected. Process will shutdown');
                                    ^

TypeError: Cannot read properties of undefined (reading 'fatal')
    at process.<anonymous> (/Users/abiliocoelho/www/dev/stripe/node_modules/@adonisjs/core/build/src/Ignitor/SignalsListener/index.js:50:37)
    at Object.onceWrapper (node:events:514:26)
    at process.emit (node:events:394:28)
    at process.emit (/Users/abiliocoelho/www/dev/stripe/node_modules/source-map-support/source-map-support.js:516:21)
    at process._fatalException (node:internal/process/execution:170:25)
    at processPromiseRejections (node:internal/process/promises:246:11)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

## Relevant Information
I'm using Adonis version 5, I've done all the steps for installation, but when setting up this error appears.

**Comment by tauapp** [comment]
I have the same issue.

**Comment by ammezie** [comment]
This has been fixed in the latest release.
