### ISSUE TITLE
Bug webhook constructEvent signature verification failed

### ISSUE THREAD

**Issue by arnauddoub** [mezielabs/adonis-stripe#15]
## Description
bug with `stripe.webhooks.constructEvent`
I need to use the webhook but it doesn't work in my opinion it's related to the body parser

```js
try {
  event = stripe.webhooks.constructEvent(request.body(), request.header('stripe-signature'), Env.get('STRIPE_WEBHOOK_SECRET'))
} catch (err) {
  Logger.error(`⚠️  Webhook signature verification failed.`, err.message)
  return response.badRequest()
}

```
## Package version
1.0.5

## Error Message & Stack Trace
⚠️  Webhook signature verification failed. No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

**Comment by JamesWrightDev** [comment]
Can you try using `request.raw()` instead?

```
const secret = Env.get('STRIPE_WEBHOOK_SECRET')
const header = request.header('stripe-signature')
const body = request.raw()
if (!header || !body) return response. badRequest('header or body missing')

const event = Stripe.webhooks.constructEvent(body, header, secret)
```

**Comment by arnauddoub** [comment]
same error
```
[1657525960378] ERROR (vkings-api/1682): No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
    err: {
      "type": "StripeSignatureVerificationError",
      "message": "No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing",
      "stack":
          Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
              at validateComputedSignature (/Users/arnaud.doubremelle/Sites/vkings/vkings-api/node_modules/.pnpm/stripe@8.222.0/node_modules/stripe/lib/Webhooks.js:208:11)
              at Object.verifyHeader (/Users/arnaud.doubremelle/Sites/vkings/vkings-api/node_modules/.pnpm/stripe@8.222.0/node_modules/stripe/lib/Webhooks.js:103:5)
              at Object.constructEvent (/Users/arnaud.doubremelle/Sites/vkings/vkings-api/node_modules/.pnpm/stripe@8.222.0/node_modules/stripe/lib/Webhooks.js:10:20)
              at CheckoutSessionController.completed (/Users/arnaud.doubremelle/Sites/vkings/vkings-api/app/Controllers/Http/Webhooks/Stripe/CheckoutSessionController.ts:14:35)
              at Injector.callAsync (/Users/arnaud.doubremelle/Sites/vkings/vkings-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "detail": {
        "header": "t=1657525960,v1=c20aebfd556f1e5f6225638993ccb62380e50442335a912de78fe5b69540ef5a,v0=9587a53c811b316287c01ec875e6a5089603ce738a7d7887d34538ea4caacdfd",
        "payload": "{\n  \"id\": \"evt_1LKHQ4HdxK6O7JbDhOqGMjRj\",\n  \"object\": \"event\",\n  \"api_version\": \"2020-08-27\",\n  \"created\": 1657525960,\n  \"data\": {\n    \"object\": {\n      \"id\": \"cs_test_a1lSK8wyU8fBzPHtILSSVvNUsWWJUTVyACjvNpOP2vfwW5Xl9i22cSRxPy\",\n      \"object\": \"checkout.session\",\n      \"after_expiration\": null,\n      \"allow_promotion_codes\": null,\n      \"amount_subtotal\": 3000,\n      \"amount_total\": 3000,\n      \"automatic_tax\": {\n        \"enabled\": false,\n        \"status\": null\n      },\n      \"billing_address_collection\": null,\n      \"cancel_url\": \"https://httpbin.org/post\",\n      \"client_reference_id\": null,\n      \"consent\": null,\n      \"consent_collection\": null,\n      \"currency\": \"usd\",\n      \"customer\": \"cus_M2M8m9UEfywUZp\",\n      \"customer_creation\": \"always\",\n      \"customer_details\": {\n        \"address\": {\n          \"city\": null,\n          \"country\": null,\n          \"line1\": null,\n          \"line2\": null,\n          \"postal_code\": null,\n          \"state\": null\n        },\n        \"email\": \"stripe@example.com\",\n        \"name\": null,\n        \"phone\": null,\n        \"tax_exempt\": \"none\",\n        \"tax_ids\": [\n\n        ]\n      },\n      \"customer_email\": null,\n      \"expires_at\": 1657612356,\n      \"livemode\": false,\n      \"locale\": null,\n      \"metadata\": {\n      },\n      \"mode\": \"payment\",\n      \"payment_intent\": \"pi_3LKHQ0HdxK6O7JbD0Kp3VdUi\",\n      \"payment_link\": null,\n      \"payment_method_options\": {\n      },\n      \"payment_method_types\": [\n        \"card\"\n      ],\n      \"payment_status\": \"paid\",\n      \"phone_number_collection\": {\n        \"enabled\": false\n      },\n      \"recovered_from\": null,\n      \"setup_intent\": null,\n      \"shipping\": null,\n      \"shipping_address_collection\": null,\n      \"shipping_options\": [\n\n      ],\n      \"shipping_rate\": null,\n      \"status\": \"complete\",\n      \"submit_type\": null,\n      \"subscription\": null,\n      \"success_url\": \"https://httpbin.org/post\",\n      \"total_details\": {\n        \"amount_discount\": 0,\n        \"amount_shipping\": 0,\n        \"amount_tax\": 0\n      },\n      \"url\": null\n    }\n  },\n  \"livemode\": false,\n  \"pending_webhooks\": 3,\n  \"request\": {\n    \"id\": null,\n    \"idempotency_key\": null\n  },\n  \"type\": \"checkout.session.completed\"\n}"
      },
      "status": 500
    }
```

**Comment by arnauddoub** [comment]
@ammezie do you have an idea?
